### PR TITLE
[messenger] fixed uploadAttachment support for buffer

### PR DESCRIPTION
**Pull request by JonathanZWhite**
This PR addresses this issue: https://github.com/Yoctol/messaging-apis/issues/223

### CODE REVIEW

**Comment by JonathanZWhite** [comment]
PTAL @chentsulin

**Comment by chentsulin** [comment]
We should pass options into those four methods too.

https://github.com/JonathanZWhite/messaging-apis/blob/32a29e24e1edeb7e56b7c415da83af7933fddf26/packages/messaging-api-messenger/src/MessengerClient.js#L1245-L1252

**Comment by JonathanZWhite** [comment]
Thanks for catching that. Updated my PR 😄

**Comment by chentsulin** [comment]
Released as https://github.com/Yoctol/messaging-apis/releases/tag/v0.5.13

**Pull request merged**
